// <auto-generated />
namespace InvestMent.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class renameModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201902251031468_renameModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
