//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestMent.Persistence.DBFirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.PancakeIngredients = new HashSet<PancakeIngredient>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> IngredientBrandId { get; set; }
        public long TypeId { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PancakeIngredient> PancakeIngredients { get; set; }
        public virtual IngredientType IngredientType { get; set; }
    }
}
