//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestMent.Persistence.DBFirstApproach
{
    using InvestMent.Domain.Interfaces.DAL;
    using System;
    using System.Collections.Generic;
    
    public partial class Pancake
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pancake()
        {
            this.PancakeIngredients = new HashSet<PancakeIngredient>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string ImageURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PancakeIngredient> PancakeIngredients { get; set; }
    }
}
